export { WSChannel, type IWSChannel, type Logger, type WSChannelOptions } from "./lib/isecure.class.js";
export { isLogLevel, isMode, parseLogLevel, parseMode } from "./lib/guards.js";
export {
  ISecureAbortError,
  ISecureError,
  ISecureHttpError,
  ISecureNetworkError,
  isISecureError,
} from "./lib/errors.js";
export { redactUrl, redactValue, type RedactionMode } from "./lib/redact.js";
export { SDK_VERSION, USER_AGENT } from "./lib/version.js";
export {
  classifyErrorReason,
  cognitoToMethod,
  methodToCognito,
  type AuthErrorReason,
  type AuthPromptAdapter,
  type AuthResponse,
  type AuthState,
  type AuthStep,
  type ResponseEnvelope,
  type SessionTokens,
  type TotpEnrollment,
} from "./lib/auth.js";
export {
  AxiosTransport,
  FakeTransport,
  LoggingTransport,
  type AxiosTransportOptions,
  type HttpHeaders,
  type HttpMethod,
  type LoggingTransportOptions,
  type QueryParams,
  type Transport,
  type TransportLogger,
  type TransportRequest,
  type TransportResponse,
} from "./lib/transport.js";
export {
  SUPPORTED_OPERATIONS,
  UNSUPPORTED_OPERATIONS,
  type ApiErrorResponse,
  type ApiResponse,
  type BankConnectionCertificateDescriptor,
  type BankConnectionDescriptor,
  type ConfigCertsRequest,
  type ConfigCertsResponse,
  type DeleteFileResponse,
  type DeleteKeyRequest,
  type DeleteKeyResponse,
  type DownloadFileResponse,
  type EnrollCertRequest,
  type EnrollCertResponse,
  type ExportCertQuery,
  type ExportCertResponse,
  type ImportCertRequest,
  type ImportCertResponse,
  type InitLoginResponse,
  type InitRegisterResponse,
  type InitPasswordResetResponse,
  type ListAccountsResponse,
  type ListCertsResponse,
  type ListFilesQuery,
  type ListFilesResponse,
  type ListKeysResponse,
  type LogLevel,
  type LoginMfaRequest,
  type LoginMfaResponse,
  type LoginRequest,
  type LoginResponse,
  type Mode,
  type OperationId,
  type PasswordResetRequest,
  type PasswordResetResponse,
  type PgpKeyPurpose,
  type RegisterRequest,
  type RegisterResponse,
  type SelectMfaRequest,
  type SelectMfaResponse,
  type ShareCertsResponse,
  type SupportedOperation,
  type UnshareCertsResponse,
  type UploadFileRequest,
  type UploadKeyRequest,
  type VerifyEmailRequest,
  type VerifyPhoneRequest,
  type VerifyTotpRequest,
  type VerifyTotpResponse,
} from "./lib/api-types.js";
export type { components, operations, paths } from "./generated/wsapi-v2.js";
